export const IS_NAV_EXPANDED = "IS_NAV_EXPANDED";
export const GET_ALL_FORM_SUCCESS = "GET_ALL_FORM_SUCCESS";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const DELETE_FORM_SUCCESS = "DELETE_FORM_SUCCESS";
